In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
Q = np.array([
    [11, 0, 0],
    [0, 0, 60],
    [0, 0, 0]
])

def to_latex(A):
    S = np.array2string(A, max_line_width=np.inf, formatter={'float_kind':lambda x: "%.3f" % x})
    S = S.replace('[', '').replace(']', '')
    R = ' \\\\ '.join(' & '.join(r.split()) for r in S.splitlines())
    return '\\begin{bmatrix} ' + R + ' \\end{bmatrix}'

In [4]:
""" Part 1 """
S_A, S_B, S_C = 0, 1, 2
A_a, A_b, A_c = 0, 1, 2
S = [ -1, S_A, S_B, S_A, S_B, S_C, S_A, S_C ]
A = [ -1, -1, A_a, A_b, A_c, A_b, A_a, A_c ]
R = [ -1, -1, 100, 60, 70, 40, 20, 0 ]

Q0 = np.zeros((3,3))
Q1 = np.zeros((3,3))
Q2 = np.array([
    [11, 0, 0],
    [0, 0, 60],
    [0, 0, 0]
])

la = 0.5
al = 0.1

"""
    We know that a_1 is a since at t=2 we have been in two states and tried two actions; (A, a) and (B, c).
    Since we are in state A at t=1 (S_1=A), we know that a_1 = a.
        a_1 = a,
    We now work backwards
        Q_2[S_1, a_1] = Q_1[S_1, a_1] + al * (R[S_1, a_1] + la * max(Q1[S_2, :]) - Q1[S_1, a_1])
                    = 0 + 0.1 * (x + 0.5 * 11 - 0) = 11
"""
S[1] = S_A
A[1] = A_a
Q2[S[1], A[1]] = 11
R[1] = Q2[S[1], A[1]] / al - la * np.max(Q2[S[2], :])

"""
    We know that a_1 is a since at t=2 we have been in two states and tried two actions; (A, a) and (B, c).
    Since we are in state A at t=1 (S_1=A), we know that S_0 = B and as such a_0 = c
        S_0 = B,
        a_0 = c,
    We now work backwards
        Q_1[S_0, a_0] = Q_0[S_0, a_0] + al * (R[S_0, a_0] + la * max(Q1[S_1, :]) - Q0[S_0, a_0])
                    = 0 + 0.1 * (x + 0.5 * 60 - 0) = 60
    
"""
S[0] = S_B
A[0] = A_c
Q1[S[0], A[0]] = 60
R[0] = Q1[S[0], A[0]] / al - np.max(Q0[S[1], :])


""" A) """
print(f'A: {A}')
print(f'S: {S}')
print(f'R: {R}')

A: [2, 0, 0, 1, 2, 1, 0, 2]
S: [1, 0, 1, 0, 1, 2, 0, 2]
R: [600.0, 80.0, 100, 60, 70, 40, 20, 0]


In [5]:
""" B) """
Q0 = np.zeros((3,3))
print('\\begin{align*}')
for i, (a, s, r, s_) in enumerate(zip(A, S, R, S[1:])):
    print(f"Q_{i+1}(a_{i}, s_{i}) &= Q_{i}(a_{i}, s_{i}) + \\alpha (R_{i} + \\lambda \\max Q_{i}(s_{i}, a') - Q_{i}(s_{i}, a_{i}))")
    print(f"= {Q0[s, a]:.1f} + {al} ({r:.1f} + {la} \\max {tuple(Q0[s_, :])} - {Q0[s, a]:.1f})")
    Q0[s, a] = Q0[s, a] + al * (r + la * max(Q0[s_, :]) - Q0[s, a])
    print(f"= {Q0[s, a]:.2f} \\\\")
print('\\end{align*}')

print(to_latex(Q0))

\begin{align*}
Q_1(a_0, s_0) &= Q_0(a_0, s_0) + \alpha (R_0 + \lambda \max Q_0(s_0, a') - Q_0(s_0, a_0))
= 0.0 + 0.1 (600.0 + 0.5 \max (0.0, 0.0, 0.0) - 0.0)
= 60.00 \\
Q_2(a_1, s_1) &= Q_1(a_1, s_1) + \alpha (R_1 + \lambda \max Q_1(s_1, a') - Q_1(s_1, a_1))
= 0.0 + 0.1 (80.0 + 0.5 \max (0.0, 0.0, 60.0) - 0.0)
= 11.00 \\
Q_3(a_2, s_2) &= Q_2(a_2, s_2) + \alpha (R_2 + \lambda \max Q_2(s_2, a') - Q_2(s_2, a_2))
= 0.0 + 0.1 (100.0 + 0.5 \max (11.0, 0.0, 0.0) - 0.0)
= 10.55 \\
Q_4(a_3, s_3) &= Q_3(a_3, s_3) + \alpha (R_3 + \lambda \max Q_3(s_3, a') - Q_3(s_3, a_3))
= 0.0 + 0.1 (60.0 + 0.5 \max (10.55, 0.0, 60.0) - 0.0)
= 9.00 \\
Q_5(a_4, s_4) &= Q_4(a_4, s_4) + \alpha (R_4 + \lambda \max Q_4(s_4, a') - Q_4(s_4, a_4))
= 60.0 + 0.1 (70.0 + 0.5 \max (0.0, 0.0, 0.0) - 60.0)
= 61.00 \\
Q_6(a_5, s_5) &= Q_5(a_5, s_5) + \alpha (R_5 + \lambda \max Q_5(s_5, a') - Q_5(s_5, a_5))
= 0.0 + 0.1 (40.0 + 0.5 \max (11.0, 9.0, 0.0) - 0.0)
= 4.55 \\
Q_7(a_6, s_6) &= Q_6(a_6, s_6) + \alpha (R_6 + \lambda \max

In [6]:
""" B) """
Q0 = np.zeros((3,3))
print(Q0)
for i, (a, s, r) in enumerate(zip(A, S, R)):
    Q0[s, a] = Q0[s, a] + al * (r + la * max(Q0[s, :]) - Q0[s, a])
    print(Q0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
[[ 8.  0.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
[[ 8.  0.  0.]
 [13.  0. 60.]
 [ 0.  0.  0.]]
[[ 8.   6.4  0. ]
 [13.   0.  60. ]
 [ 0.   0.   0. ]]
[[ 8.   6.4  0. ]
 [13.   0.  64. ]
 [ 0.   0.   0. ]]
[[ 8.   6.4  0. ]
 [13.   0.  64. ]
 [ 0.   4.   0. ]]
[[ 9.6  6.4  0. ]
 [13.   0.  64. ]
 [ 0.   4.   0. ]]
[[ 9.6  6.4  0. ]
 [13.   0.  64. ]
 [ 0.   4.   0.2]]


In [7]:
""" C) """
pi_A = np.argmax(Q0[S_A, :])
pi_B = np.argmax(Q0[S_B, :])
pi_C = np.argmax(Q0[S_C, :])
print(f'pi_A: {pi_A}')
print(f'pi_B: {pi_B}')
print(f'pi_C: {pi_C}')

pi_A: 0
pi_B: 2
pi_C: 1


In [8]:
""" D) """
Q0 = np.zeros((3,3))
print('\\begin{align*}')
for i, (a, s, r, s_, a_) in enumerate(zip(A, S, R, S[1:], A[1:])):
    print(f"Q_{i+1}(a_{i}, s_{i}) &= Q_{i}(a_{i}, s_{i}) + \\alpha (R_{i} + \\lambda Q_{i}(s_{i+1}, a_{i+1}) - Q_{i}(s_{i}, a_{i}))")
    print(f"= {Q0[s, a]:.1f} + {al} ({r:.1f} + {la} \\cdot {Q0[s_, a_]:.2f} - {Q0[s, a]:.2f})")
    Q0[s, a] = Q0[s, a] + al * (r + la * Q0[s_, a_] - Q0[s, a])
    print(f"= {Q0[s, a]:.2f} \\\\")
print('\\end{align*}')

print(to_latex(Q0))

\begin{align*}
Q_1(a_0, s_0) &= Q_0(a_0, s_0) + \alpha (R_0 + \lambda Q_0(s_1, a_1) - Q_0(s_0, a_0))
= 0.0 + 0.1 (600.0 + 0.5 \cdot 0.00 - 0.00)
= 60.00 \\
Q_2(a_1, s_1) &= Q_1(a_1, s_1) + \alpha (R_1 + \lambda Q_1(s_2, a_2) - Q_1(s_1, a_1))
= 0.0 + 0.1 (80.0 + 0.5 \cdot 0.00 - 0.00)
= 8.00 \\
Q_3(a_2, s_2) &= Q_2(a_2, s_2) + \alpha (R_2 + \lambda Q_2(s_3, a_3) - Q_2(s_2, a_2))
= 0.0 + 0.1 (100.0 + 0.5 \cdot 0.00 - 0.00)
= 10.00 \\
Q_4(a_3, s_3) &= Q_3(a_3, s_3) + \alpha (R_3 + \lambda Q_3(s_4, a_4) - Q_3(s_3, a_3))
= 0.0 + 0.1 (60.0 + 0.5 \cdot 60.00 - 0.00)
= 9.00 \\
Q_5(a_4, s_4) &= Q_4(a_4, s_4) + \alpha (R_4 + \lambda Q_4(s_5, a_5) - Q_4(s_4, a_4))
= 60.0 + 0.1 (70.0 + 0.5 \cdot 0.00 - 60.00)
= 61.00 \\
Q_6(a_5, s_5) &= Q_5(a_5, s_5) + \alpha (R_5 + \lambda Q_5(s_6, a_6) - Q_5(s_5, a_5))
= 0.0 + 0.1 (40.0 + 0.5 \cdot 8.00 - 0.00)
= 4.40 \\
Q_7(a_6, s_6) &= Q_6(a_6, s_6) + \alpha (R_6 + \lambda Q_6(s_7, a_7) - Q_6(s_6, a_6))
= 8.0 + 0.1 (20.0 + 0.5 \cdot 0.00 - 8.00)
= 9.20 \\
\end

In [9]:
""" D) SARSA """
Q0 = np.zeros((3,3))
print(f'{0}:\n', Q0)
for i, (a, s, r, s_, a_) in enumerate(zip(A, S, R, S[1:], A[1:])):
    Q0[s, a] = Q0[s, a] + al * (r + la * Q0[s_, a_] - Q0[s, a])
    print(f'{i+1}:\n', Q0)

0:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1:
 [[ 0.  0.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
2:
 [[ 8.  0.  0.]
 [ 0.  0. 60.]
 [ 0.  0.  0.]]
3:
 [[ 8.  0.  0.]
 [10.  0. 60.]
 [ 0.  0.  0.]]
4:
 [[ 8.  9.  0.]
 [10.  0. 60.]
 [ 0.  0.  0.]]
5:
 [[ 8.  9.  0.]
 [10.  0. 61.]
 [ 0.  0.  0.]]
6:
 [[ 8.   9.   0. ]
 [10.   0.  61. ]
 [ 0.   4.4  0. ]]
7:
 [[ 9.2  9.   0. ]
 [10.   0.  61. ]
 [ 0.   4.4  0. ]]


In [10]:
""" E) """
pi_A = np.argmax(Q0[S_A, :])
pi_B = np.argmax(Q0[S_B, :])
pi_C = np.argmax(Q0[S_C, :])
print(f'pi_A: {pi_A}')
print(f'pi_B: {pi_B}')
print(f'pi_C: {pi_C}')

pi_A: 0
pi_B: 2
pi_C: 1


In [11]:
""" F)
    The rewards are probably not deterministic,
    since t=0 and t=4 have the same state and action but different rewards.
"""
print(f'S: {S}')
print(f'A: {A}')
print(f'R: {R}')

S: [1, 0, 1, 0, 1, 2, 0, 2]
A: [2, 0, 0, 1, 2, 1, 0, 2]
R: [600.0, 80.0, 100, 60, 70, 40, 20, 0]


In [12]:
""" Part 2 """
n = 3
p = np.random.uniform(0, 1, size=(n,))

f = lambda s: 1 / (1 + np.exp(-0.1*s)) + 1
def v(s, P):
    Z = np.random.uniform(0, 1, size=(n,)) * f(s)
    for i, z, p in zip(range(n), Z, P):
        if z < p:
            return i + 1
    return n + 1

s = 3
fs = f(s)
print((1 - p[0] / f(s)) * p[1] / fs)
N = 200000
k = 0
for _ in range(N):
    k += v(s, p) == 2
print(k / N)

0.25485197844975094


0.254105


In [13]:
""" A) 
1)
    pi_theta(s, 1) = int_0^f(s) delta(z < p_1) dz / int_0^f(s) dz
                    = f(s)^{-1} int_0^f(s) delta(z < p_1) dz
                = f(s)^{-1} int_0^min(p_1, f(s)) dz
                = p_1 / f(s)
2)
    pi_theta(s, 2) = (1 - pi_theta(s, 1)) int_0^f(s) delta(z < p_2) dz / int_0^f(s) dz
                    = p_2 / f(s) * (1 - p_1 / f(s))
3)
    pi_theta(s, n+1) = prod_{i=1}^n (1 - p_i / f(s))
"""

' A) \n1)\n    pi_theta(s, 1) = int_0^f(s) delta(z < p_1) dz / int_0^f(s) dz\n                    = f(s)^{-1} int_0^f(s) delta(z < p_1) dz\n                = f(s)^{-1} int_0^min(p_1, f(s)) dz\n                = p_1 / f(s)\n2)\n    pi_theta(s, 2) = (1 - pi_theta(s, 1)) int_0^f(s) delta(z < p_2) dz / int_0^f(s) dz\n                    = p_2 / f(s) * (1 - p_1 / f(s))\n3)\n    pi_theta(s, n+1) = prod_{i=1}^n (1 - p_i / f(s))\n'

In [14]:
""" B)
1)
    \frac{\partial ln(pi_theta(s, i))}{\partial p_i}
                        = \frac{\partial ln(p_1 / f(s))}{\partial p_i}
                        = 1 / p_1
2)
    if k < i
    \frac{\partial ln(pi_theta(s, i))}{\partial p_k}
                        = \frac{\partial ln(
                            p_i / f(s) prod_{j=1}^{i-1} (1 - p_j / f(s))
                        )}{\partial p_k}
                        = \frac{\partial ln(
                            1 - p_k / f(s)
                        )}{\partial p_k}
                        = -1 / f(s) * 1 / (1 - p_k / f(s))
                        = 1 / (p_k - f(s))
3)
    if i < k
    \frac{\partial ln(pi_theta(s, i))}{\partial p_k}
                        = \frac{\partial ln(
                            p_i / f(s) prod_{j=1}^{i-1} (1 - p_j / f(s))
                        )}{\partial p_k}
                        =
                        0
"""

' B)\n1)\n    \x0crac{\\partial ln(pi_theta(s, i))}{\\partial p_i}\n                        = \x0crac{\\partial ln(p_1 / f(s))}{\\partial p_i}\n                        = 1 / p_1\n2)\n    if k < i\n    \x0crac{\\partial ln(pi_theta(s, i))}{\\partial p_k}\n                        = \x0crac{\\partial ln(\n                            p_i / f(s) prod_{j=1}^{i-1} (1 - p_j / f(s))\n                        )}{\\partial p_k}\n                        = \x0crac{\\partial ln(\n                            1 - p_k / f(s)\n                        )}{\\partial p_k}\n                        = -1 / f(s) * 1 / (1 - p_k / f(s))\n                        = 1 / (p_k - f(s))\n3)\n    if i < k\n    \x0crac{\\partial ln(pi_theta(s, i))}{\\partial p_k}\n                        = \x0crac{\\partial ln(\n                            p_i / f(s) prod_{j=1}^{i-1} (1 - p_j / f(s))\n                        )}{\\partial p_k}\n                        =\n                        0\n'

In [15]:
""" C)
w = normal(0, 1, size=(p,))

for episode in range(num_episodes):
    s = s0
    done = False
    while not done:
        a = policy(s) # perhaps epsilon-greedy
        s_next, r, done = env.step(a)

        delta = r + gamma * v(s_next, w) - v(s, w)
        w = w + alpha * delta * grad_v(s, w)
        s = s_next

it is a semi-gradient algorithm because the gradient is not taken with respect to the policy parameters,
it is taken with respect to the value function parameters.
"""

' C)\nw = normal(0, 1, size=(p,))\n\nfor episode in range(num_episodes):\n    s = s0\n    done = False\n    while not done:\n        a = policy(s) # perhaps epsilon-greedy\n        s_next, r, done = env.step(a)\n\n        delta = r + gamma * v(s_next, w) - v(s, w)\n        w = w + alpha * delta * grad_v(s, w)\n        s = s_next\n\nit is a semi-gradient algorithm because the gradient is not taken with respect to the policy parameters,\nit is taken with respect to the value function parameters.\n'

In [16]:
""" D)
The target is the value function, which is updated in every step.
This could affect the convergence because the value function is not stationary.
We can address this problem by using a target value function, which is not updated in every step.
Like n-step SARSA.
"""

' D)\nThe target is the value function, which is updated in every step.\nThis could affect the convergence because the value function is not stationary.\nWe can address this problem by using a target value function, which is not updated in every step.\nLike n-step SARSA.\n'